export const dummyData = {
  data: {
    games: [
      {
        code: "HJ-72IFXyg",
        nameEn: "Stay On The Road",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Stay On The Road",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HyV_Nm-kK",
        nameEn: "Super Sprint",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Super Sprint",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "Sk728YXJx",
        nameEn: "Pixel Slime",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Pixel Slime",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BJlg94zA76",
        nameEn: "Zigzag Clash",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Zigzag Clash",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "B1MfIa4QCg",
        nameEn: "Spider Solitaire",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Spider Solitaire",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "S1-bxXI39",
        nameEn: "Monsterjong",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Monsterjong",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "4ykgM_yzbcg",
        nameEn: "Rescue Juliet",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Rescue Juliet",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SyjAFr-dE",
        nameEn: "Jom Jom Jump",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Jom Jom Jump",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rJDlAKHbdV",
        nameEn: "Sir Bottomtight",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Sir Bottomtight",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "B1MXhUFQke",
        nameEn: "Tower Loot",
        battleSupported: false,
        rating: 4.75,
        totalRating: 1,
        name: "Tower Loot",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "S1JfKuB9nR",
        nameEn: "Foot Chinko",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Foot Chinko",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SJz7-kTud",
        nameEn: "Submarine Dash",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Submarine Dash",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "ryRWrDaNPF",
        nameEn: "Dodgy",
        battleSupported: false,
        rating: 4.75,
        totalRating: 1,
        name: "Dodgy",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "Hkww3v3-F",
        nameEn: "Fly Safe",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Fly Safe",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BJ9ZE86I6Wg",
        nameEn: "Aqua Thief",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Aqua Thief",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SJXbW8smUUx",
        nameEn: "Quack Hunt",
        battleSupported: false,
        rating: 4.75,
        totalRating: 1,
        name: "Quack Hunt",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rk-Rtrb_V",
        nameEn: "Blackbeard's Island",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Blackbeard's Island",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rkXGK1_L",
        nameEn: "Monster Wants Candy",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Monster Wants Candy",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rkWemI2q",
        nameEn: "Fancy Diver",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Fancy Diver",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HJD9VMRQa",
        nameEn: "Astro Knot",
        battleSupported: false,
        rating: 2.75,
        totalRating: 1,
        name: "Astro Knot",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HJE-oa2z_l-",
        nameEn: "Mirror Me",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Mirror Me",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "r1ozpMkD5Jm",
        nameEn: "Kickin It",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Kickin It",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "r1zCFBZdV",
        nameEn: "Defense of Karmax 3",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Defense of Karmax 3",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HyCKrWd4",
        nameEn: "Basketball Master",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Basketball Master",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "ry8RYrWu4",
        nameEn: "Evil Wyrm",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Evil Wyrm",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "EJnzu1fb9g",
        nameEn: "Crunching Ninjas",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Crunching Ninjas",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "NJ8gGuyMZ5e",
        nameEn: "Pie Attack",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Pie Attack",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "B1SlRFrWuN",
        nameEn: "Robotion",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Robotion",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "Sy6RYB-u4",
        nameEn: "Little Bouncing Guys",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Little Bouncing Guys",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "ByGqEfCXa",
        nameEn: "Falling Through",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Falling Through",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "EJaG_JfW9l",
        nameEn: "Groovy Ski",
        battleSupported: false,
        rating: 4.75,
        totalRating: 2,
        name: "Groovy Ski",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "B1hCYSbdN",
        nameEn: "Let's Go Fishing",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Let's Go Fishing",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SkRWoanGOx",
        nameEn: "Catch-a-pult",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Catch-a-pult",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BkqTS_1b",
        nameEn: "Oh No",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Oh No",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SklmW1ad_",
        nameEn: "Let Me Grow",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Let Me Grow",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "H13-Z8sQILx",
        nameEn: "Blackjack 21 Pro",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Blackjack 21 Pro",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SkhljT2fdgb",
        nameEn: "Ludo With Friends",
        battleSupported: false,
        rating: 3.58,
        totalRating: 12,
        name: "Ludo With Friends",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BJ9bvzIKdJl",
        nameEn: "Brick Plunge",
        battleSupported: false,
        rating: 3.63,
        totalRating: 4,
        name: "Brick Plunge",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rJsl0KSbuN",
        nameEn: "Swipe Art Puzzle",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Swipe Art Puzzle",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "VJOGOyGb9l",
        nameEn: "Flying School",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Flying School",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BydCYS-ON",
        nameEn: "Greedy Gnomes",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Greedy Gnomes",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SJMB7qTb",
        nameEn: "Ooltaa",
        battleSupported: false,
        rating: 4.75,
        totalRating: 1,
        name: "Ooltaa",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "ByvOVQZkK",
        nameEn: "Skill Shot",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Skill Shot",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BJzGTMJv91Q",
        nameEn: "Gerbil Jump",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Gerbil Jump",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "4kZgf_1z-9l",
        nameEn: "Lane Battles",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Lane Battles",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SJcRYSbu4",
        nameEn: "Jelly Bears",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Jelly Bears",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SJ3-ELT8p-x",
        nameEn: "Jelly Slice",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Jelly Slice",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "S14VrK8B",
        nameEn: "Pixel Zombies",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Pixel Zombies",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rkwCYBZuV",
        nameEn: "Furious Speed",
        battleSupported: false,
        rating: 4.38,
        totalRating: 4,
        name: "Furious Speed",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "N1sZfO1fWqg",
        nameEn: "Grumpy Gorilla",
        battleSupported: false,
        rating: 4.75,
        totalRating: 1,
        name: "Grumpy Gorilla",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "H1abja2M_eb",
        nameEn: "Hex Burst",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Hex Burst",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HJee0YHZ_E",
        nameEn: "Penguin Skip",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Penguin Skip",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HkBWwMUFOye",
        nameEn: "Terra Infirma",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Terra Infirma",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "Bk25EzR7T",
        nameEn: "Slit Sight",
        battleSupported: false,
        rating: 4.75,
        totalRating: 1,
        name: "Slit Sight",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rJJMVIa8p-x",
        nameEn: "Sticky Goo",
        battleSupported: false,
        rating: 4,
        totalRating: 4,
        name: "Sticky Goo",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BJm9VfCmp",
        nameEn: "Watch The Walls",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Watch The Walls",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "ry3vtunu",
        nameEn: "Battle Fish",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Battle Fish",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SyO94GA7p",
        nameEn: "Super Goalie Auditions",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Super Goalie Auditions",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rkb--Io78Ux",
        nameEn: "Tiny Tripper",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Tiny Tripper",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rJsWV8aIa-l",
        nameEn: "Jelly Doods",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Jelly Doods",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "B1H5NfCXa",
        nameEn: "Homerun Hit",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Homerun Hit",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BJlMwGUY_yl",
        nameEn: "Sheriff's Wrath",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Sheriff's Wrath",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "r1Xm38FQkl",
        nameEn: "Alien Kindergarten",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Alien Kindergarten",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SyN0KSWuV",
        nameEn: "Crazy Pizza",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Crazy Pizza",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SykGDfUKOkg",
        nameEn: "Traffic Command",
        battleSupported: false,
        rating: 4.08,
        totalRating: 3,
        name: "Traffic Command",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rJWX-kadu",
        nameEn: "Salazar",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Salazar",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HkO-wf8F_Jx",
        nameEn: "Jumpy: The First Jumper",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Jumpy: The First Jumper",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "Ske-CtBbdV",
        nameEn: "Zoo Pinball",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Zoo Pinball",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "r1xZj62MOe-",
        nameEn: "Aquatic Rescue",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Aquatic Rescue",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SkKlAYSbuE",
        nameEn: "Snack Time",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Snack Time",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "H1be5Ef0Qp",
        nameEn: "Vegetables vs. Chef",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Vegetables vs. Chef",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SkyRBO1b",
        nameEn: "Oh Yes",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Oh Yes",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "ByAWPfLYdJx",
        nameEn: "Trap & Kill Virus",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Trap & Kill Virus",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SysZvGUt_ye",
        nameEn: "Snappy Spy",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Snappy Spy",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rJybo6nfdgb",
        nameEn: "Ship It Up!",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Ship It Up!",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HkSWia3f_g-",
        nameEn: "Coin Grab",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Coin Grab",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BJAqNMC7T",
        nameEn: "Alfy",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Alfy",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BJ8Wb8j7ILx",
        nameEn: "Soccer Jerks",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Soccer Jerks",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SyIZjp3GulZ",
        nameEn: "Black Jack Grid",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Black Jack Grid",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "Hy2xAKHb_V",
        nameEn: "Troll Boxing",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Troll Boxing",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "Sy6b98udz0",
        nameEn: "Cuby Dash",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Cuby Dash",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SyFcNzAX6",
        nameEn: "Shade Shuffle",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Shade Shuffle",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "r1fl9VzRX6",
        nameEn: "Pirate's Pillage! Aye! Aye!",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Pirate's Pillage! Aye! Aye!",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "H1pbZUoXIUl",
        nameEn: "Save Your Pinky",
        battleSupported: false,
        rating: 3.5,
        totalRating: 2,
        name: "Save Your Pinky",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HJeM-LsQI8x",
        nameEn: "Cuby Zap",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Cuby Zap",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "N1tgz_kzW5x",
        nameEn: "Aliens Attack",
        battleSupported: false,
        rating: 4.75,
        totalRating: 1,
        name: "Aliens Attack",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SyXuN7W1F",
        nameEn: "Rocket Man",
        battleSupported: false,
        rating: 4.25,
        totalRating: 6,
        name: "Rocket Man",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BJrMI6E7Rl",
        nameEn: "Twin Hop",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Twin Hop",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SkRZZUoXI8g",
        nameEn: "Jello Go Round",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Jello Go Round",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HJKWbUj788l",
        nameEn: "Clay Pigeon: Tap and Shoot",
        battleSupported: false,
        rating: 4.25,
        totalRating: 2,
        name: "Clay Pigeon: Tap and Shoot",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "r1z-eQ8nq",
        nameEn: "Road Safety",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Road Safety",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HyIM86VXAe",
        nameEn: "Hats Off",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Hats Off",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HkRMTzJDck7",
        nameEn: "Rollout",
        battleSupported: false,
        rating: 3.75,
        totalRating: 7,
        name: "Rollout",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "ryN9EGAQa",
        nameEn: "Slap Fest",
        battleSupported: false,
        rating: 4.12,
        totalRating: 23,
        name: "Slap Fest",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HyZMUTVQRe",
        nameEn: "Where's the Ace?",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Where's the Ace?",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "Bk4ML6470x",
        nameEn: "Odd One Out",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Odd One Out",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "H1eGU64XRg",
        nameEn: "High or Low",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "High or Low",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "H1Tz6z1Dqym",
        nameEn: "Bouncy",
        battleSupported: false,
        rating: 2.75,
        totalRating: 1,
        name: "Bouncy",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "ry6bwfUt_Jg",
        nameEn: "Savage Revenge",
        battleSupported: false,
        rating: 3.75,
        totalRating: 9,
        name: "Savage Revenge",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "Sy64_WbU",
        nameEn: "Punch Heroes",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Punch Heroes",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SyQZs6nzueW",
        nameEn: "The Sea Lion Act",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "The Sea Lion Act",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BkpeAKrW_E",
        nameEn: "Veggi Rabbit",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Veggi Rabbit",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "NyM_JGWcx",
        nameEn: "2048",
        battleSupported: false,
        rating: 3.25,
        totalRating: 3,
        name: "2048",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rkHuVQ-1K",
        nameEn: "Illuminate",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Illuminate",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SJghvtd2_",
        nameEn: "Drop Me",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Drop Me",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SkQwnwnbK",
        nameEn: "Flexi Snake",
        battleSupported: false,
        rating: 4.08,
        totalRating: 3,
        name: "Flexi Snake",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "H1lZem8hq",
        nameEn: "Juicy Dash",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Juicy Dash",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BJdZ-8iXULl",
        nameEn: "Nut Physics",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Nut Physics",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SkGIa4X0l",
        nameEn: "Pai Gow Poker",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Pai Gow Poker",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BkXW1a__",
        nameEn: "Jimbo Jump",
        battleSupported: false,
        rating: 4.25,
        totalRating: 3,
        name: "Jimbo Jump",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SkJf58Ouf0",
        nameEn: "Dribble Kings",
        battleSupported: false,
        rating: 4.75,
        totalRating: 2,
        name: "Dribble Kings",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "V1IZG_1f-qg",
        nameEn: "Sheep Stacking",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Sheep Stacking",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "S1VZ-LjQUUl",
        nameEn: "Fizz Fuss",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Fizz Fuss",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "S1Clo6hMdeb",
        nameEn: "Jumpy Ape Joe",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Jumpy Ape Joe",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "S1kGWUim8Ux",
        nameEn: "Shadow Run",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Shadow Run",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "4y6efOyf-5g",
        nameEn: "Bouncing Beasts",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Bouncing Beasts",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HJXei0j",
        nameEn: "Cyberfusion",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Cyberfusion",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "41FZfdyG-5x",
        nameEn: "1212!",
        battleSupported: false,
        rating: 2.75,
        totalRating: 1,
        name: "1212!",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "4JcZiV3XWql",
        nameEn: "Rafting Adventure",
        battleSupported: false,
        rating: 2.75,
        totalRating: 3,
        name: "Rafting Adventure",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "B1PMIp4XCe",
        nameEn: "Sway Bay",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Sway Bay",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "S1A0FBWuE",
        nameEn: "Minigolf Kingdom",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Minigolf Kingdom",
        categories: ["sportsRacing"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SyTeia3fOeZ",
        nameEn: "Cowboy vs. Martians",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Cowboy vs. Martians",
        categories: ["puzzleLogic"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "EJoezu1MWqg",
        nameEn: "Rock the Dock",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Rock the Dock",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rJyWCKHbON",
        nameEn: "Yummy Taco",
        battleSupported: false,
        rating: 4.75,
        totalRating: 1,
        name: "Yummy Taco",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rkxMV8TI6Wg",
        nameEn: "Zombies Can't Jump 2",
        battleSupported: false,
        rating: 4.18,
        totalRating: 7,
        name: "Zombies Can't Jump 2",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "BJ-ZsT2zOeZ",
        nameEn: "One More Flight",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "One More Flight",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "NkxfOJM-qg",
        nameEn: "Fidgety Frog",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Fidgety Frog",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rkYbNLTIT-x",
        nameEn: "Knight Ride",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Knight Ride",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "HkxQnLtmJe",
        nameEn: "Rabbit Punch",
        battleSupported: false,
        rating: 2.75,
        totalRating: 1,
        name: "Rabbit Punch",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "r10-NLT86bx",
        nameEn: "Rope Ninja",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Rope Ninja",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "NJ3xGOyfb5l",
        nameEn: "Tricky Trip",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Tricky Trip",
        categories: ["arcade"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "SJ2OGpIn",
        nameEn: "Dodge Bot",
        battleSupported: false,
        rating: 4.75,
        totalRating: 1,
        name: "Dodge Bot",
        categories: ["adventure"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "H1TbVUa8aWe",
        nameEn: "Pebble Boy",
        battleSupported: false,
        rating: 4.75,
        totalRating: 1,
        name: "Pebble Boy",
        categories: ["strategy"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "rJXlRtBWd4",
        nameEn: "Pumpkin Smasher",
        battleSupported: false,
        rating: 3.78,
        totalRating: 17,
        name: "Pumpkin Smasher",
        categories: ["action"],
        created_at: "2019-02-08T11:32:36.637Z",
        gamePlays: 0,
      },
      {
        code: "S1JXaMJDqJX",
        nameEn: "Cubes Got Moves",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Cubes Got Moves",
        categories: ["puzzleLogic"],
        created_at: "2019-02-15T13:30:04.005Z",
        gamePlays: 0,
      },
      {
        code: "BkzmafyPqJm",
        nameEn: "Cricket Gunda",
        battleSupported: false,
        rating: 3.75,
        totalRating: 6,
        name: "Cricket Gunda",
        categories: ["sportsRacing"],
        created_at: "2019-03-13T13:39:01.842Z",
        gamePlays: 0,
      },
      {
        code: "H1WmafkP9JQ",
        nameEn: "Tic Tac Toe",
        battleSupported: false,
        rating: 3.85,
        totalRating: 5,
        name: "Tic Tac Toe",
        categories: ["strategy"],
        created_at: "2019-03-15T13:40:59.831Z",
        gamePlays: 0,
      },
      {
        code: "Hkh7azyv9km",
        nameEn: "Junior Chess",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Junior Chess",
        categories: ["strategy"],
        created_at: "2019-03-26T07:56:38.262Z",
        gamePlays: 0,
      },
      {
        code: "B1SmafkP5kQ",
        nameEn: "Holiday Cheer",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Holiday Cheer",
        categories: ["adventure"],
        created_at: "2019-04-04T12:36:59.116Z",
        gamePlays: 0,
      },
      {
        code: "HJP4afkvqJQ",
        nameEn: "City Cricket",
        battleSupported: false,
        rating: 4.02,
        totalRating: 11,
        name: "City Cricket",
        categories: ["sportsRacing"],
        created_at: "2019-04-10T18:43:53.967Z",
        gamePlays: 0,
      },
      {
        code: "SyEQTzyw91X",
        nameEn: "Exoplanet Express",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Exoplanet Express",
        categories: ["arcade"],
        created_at: "2019-04-15T06:19:24.530Z",
        gamePlays: 0,
      },
      {
        code: "S1_V6GyP5ym",
        nameEn: "Basket Champs",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Basket Champs",
        categories: ["sportsRacing"],
        created_at: "2019-04-15T12:30:31.143Z",
        gamePlays: 0,
      },
      {
        code: "SJX7TGkDq1X",
        nameEn: "Pop Soap",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Pop Soap",
        categories: ["puzzleLogic"],
        created_at: "2019-04-15T16:32:40.059Z",
        gamePlays: 0,
      },
      {
        code: "rJ57aMJDcJm",
        nameEn: "Go Chicken Go",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Go Chicken Go",
        categories: ["adventure"],
        created_at: "2019-04-27T14:31:32.890Z",
        gamePlays: 0,
      },
      {
        code: "BJsmaGJw91m",
        nameEn: "Happy Kittens Puzzle",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Happy Kittens Puzzle",
        categories: ["puzzleLogic"],
        created_at: "2019-05-01T13:34:01.869Z",
        gamePlays: 0,
      },
      {
        code: "rkt7TzJv9k7",
        nameEn: "Battleships Armada",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Battleships Armada",
        categories: ["strategy"],
        created_at: "2019-05-02T12:13:07.950Z",
        gamePlays: 0,
      },
      {
        code: "SJXVafJP51Q",
        nameEn: "Nosedive",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Nosedive",
        categories: ["adventure"],
        created_at: "2019-05-08T09:44:29.652Z",
        gamePlays: 0,
      },
      {
        code: "rJu76zkD917",
        nameEn: "Algerian Solitaire",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Algerian Solitaire",
        categories: ["strategy"],
        created_at: "2019-05-09T07:53:17.900Z",
        gamePlays: 0,
      },
      {
        code: "HJY4pfJP9JQ",
        nameEn: "Table Tennis Shots",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Table Tennis Shots",
        categories: ["sportsRacing"],
        created_at: "2019-05-21T05:43:23.298Z",
        gamePlays: 0,
      },
      {
        code: "B19EafJP9JX",
        nameEn: "Spinning Shooter",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Spinning Shooter",
        categories: ["arcade"],
        created_at: "2019-05-28T06:04:57.495Z",
        gamePlays: 0,
      },
      {
        code: "SkkV6MJD51Q",
        nameEn: "Mafia Billiard Tricks",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Mafia Billiard Tricks",
        categories: ["sportsRacing"],
        created_at: "2019-05-28T08:02:45.000Z",
        gamePlays: 0,
      },
      {
        code: "B1fSpMkP51m",
        nameEn: "Bottle Shoot",
        battleSupported: false,
        rating: 3.01,
        totalRating: 64,
        name: "Bottle Shoot",
        categories: ["action"],
        created_at: "2019-06-22T21:24:20.607Z",
        gamePlays: 0,
      },
      {
        code: "S1Wrpf1v5ym",
        nameEn: "Box Crush",
        battleSupported: false,
        rating: 2,
        totalRating: 1,
        name: "Box Crush",
        categories: ["puzzleLogic"],
        created_at: "2019-06-28T12:53:43.370Z",
        gamePlays: 0,
      },
      {
        code: "B1JBaM1D9y7",
        nameEn: "Colour Chase",
        battleSupported: false,
        rating: 3.4,
        totalRating: 5,
        name: "Colour Chase",
        categories: ["adventure"],
        created_at: "2019-10-15T14:05:30.389Z",
        gamePlays: 0,
      },
      {
        code: "HJT46GkPcy7",
        nameEn: "Tower Twist",
        battleSupported: false,
        rating: 2.7,
        totalRating: 5,
        name: "Tower Twist",
        categories: ["arcade"],
        created_at: "2019-10-24T13:45:21.755Z",
        gamePlays: 0,
      },
      {
        code: "H1AN6fkwqJ7",
        nameEn: "Bubble Wipeout",
        battleSupported: false,
        rating: 3.1,
        totalRating: 5,
        name: "Bubble Wipeout",
        categories: ["strategy"],
        created_at: "2019-11-01T07:09:49.234Z",
        gamePlays: 0,
      },
      {
        code: "Skz4pzkDqyX",
        nameEn: "Escape Run",
        battleSupported: false,
        rating: 3,
        totalRating: 10,
        name: "Escape Run",
        categories: ["adventure"],
        created_at: "2019-11-04T10:44:14.422Z",
        gamePlays: 0,
      },
      {
        code: "B1gBpzJwqJQ",
        nameEn: "Pirate Hunt",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Pirate Hunt",
        categories: ["action"],
        created_at: "2019-11-11T16:11:20.693Z",
        gamePlays: 0,
      },
      {
        code: "SJ8X6zyPcyX",
        nameEn: "Saloon Robbery",
        battleSupported: false,
        rating: 3.79,
        totalRating: 7,
        name: "Saloon Robbery",
        categories: ["action"],
        created_at: "2019-11-15T06:36:55.911Z",
        gamePlays: 0,
      },
      {
        code: "H1IEpMJP917",
        nameEn: "Plane Fight",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Plane Fight",
        categories: ["action"],
        created_at: "2019-12-20T15:28:36.908Z",
        gamePlays: 0,
      },
      {
        code: "B1jZWUoXUIe",
        nameEn: "Valley of Terror",
        battleSupported: false,
        rating: 2.75,
        totalRating: 1,
        name: "Valley of Terror",
        categories: ["action"],
        created_at: "2020-03-12T06:07:41.492Z",
        gamePlays: 0,
      },
      {
        code: "B1Gbjphf_gZ",
        nameEn: "Saucer Dodge",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Saucer Dodge",
        categories: ["adventure"],
        created_at: "2020-03-12T06:07:41.493Z",
        gamePlays: 0,
      },
      {
        code: "H1PJn6mqAr",
        nameEn: "Knife Flip",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Knife Flip",
        categories: ["adventure"],
        created_at: "2020-04-03T18:25:45.438Z",
        gamePlays: 0,
      },
      {
        code: "r1z13aXqAB",
        nameEn: "Flappy Foot Chinko",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Flappy Foot Chinko",
        categories: ["sportsRacing"],
        created_at: "2020-05-14T17:52:34.876Z",
        gamePlays: 0,
      },
      {
        code: "BkdJhTX50B",
        nameEn: "Bowling Stars",
        battleSupported: false,
        rating: 2.5,
        totalRating: 1,
        name: "Bowling Stars",
        categories: ["sportsRacing"],
        created_at: "2020-06-01T16:01:00.370Z",
        gamePlays: 0,
      },
      {
        code: "SyfxJ3a75Cr",
        nameEn: "Kingdom Fight",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Kingdom Fight",
        categories: ["strategy"],
        created_at: "2020-06-17T09:37:14.557Z",
        gamePlays: 0,
      },
      {
        code: "rJWyhp79RS",
        nameEn: "Snakes & Ladders",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Snakes & Ladders",
        categories: ["adventure"],
        created_at: "2020-07-10T10:52:58.776Z",
        gamePlays: 0,
      },
      {
        code: "SJgx126Qc0H",
        nameEn: "Sudoku Classic",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Sudoku Classic",
        categories: ["puzzleLogic"],
        created_at: "2020-07-24T18:22:20.312Z",
        gamePlays: 0,
      },
      {
        code: "rkAXTzkD5kX",
        nameEn: "Chess Grandmaster",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Chess Grandmaster",
        categories: ["strategy"],
        created_at: "2020-08-07T16:44:03.408Z",
        gamePlays: 0,
      },
      {
        code: "ByRkh6XcAB",
        nameEn: "Car Flip",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Car Flip",
        categories: ["arcade"],
        created_at: "2020-08-31T17:37:44.317Z",
        gamePlays: 0,
      },
      {
        code: "HJskh679Cr",
        nameEn: "Enchanted Waters",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Enchanted Waters",
        categories: ["adventure"],
        created_at: "2020-09-04T16:23:57.909Z",
        gamePlays: 0,
      },
      {
        code: "rybx12amqCB",
        nameEn: "Don't Touch the Walls",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Don't Touch the Walls",
        categories: ["adventure"],
        created_at: "2020-09-21T08:19:35.813Z",
        gamePlays: 0,
      },
      {
        code: "Hk2yhp7cCH",
        nameEn: "Tic Tac Toe 11",
        battleSupported: false,
        rating: 4,
        totalRating: 1,
        name: "Tic Tac Toe 11",
        categories: ["puzzleLogic"],
        created_at: "2020-10-01T18:27:12.502Z",
        gamePlays: 0,
      },
      {
        code: "rkmJ2aXcCS",
        nameEn: "Minesweeper Classic",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Minesweeper Classic",
        categories: ["strategy"],
        created_at: "2020-12-10T09:53:46.889Z",
        gamePlays: 0,
      },
      {
        code: "H1Hgyn6XqAS",
        nameEn: "Carrom Hero",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Carrom Hero",
        categories: ["strategy"],
        created_at: "2021-01-20T06:47:39.323Z",
        gamePlays: 0,
      },
      {
        code: "rkPlk2T7qAr",
        nameEn: "Solitaire Gold",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Solitaire Gold",
        categories: ["strategy"],
        created_at: "2021-02-10T16:52:48.243Z",
        gamePlays: 0,
      },
      {
        code: "Sk1Wyn6XqRH",
        nameEn: "Foosball Kick",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Foosball Kick",
        categories: ["sportsRacing"],
        created_at: "2021-02-23T12:07:50.171Z",
        gamePlays: 0,
      },
      {
        code: "ryTknTX5AS",
        nameEn: "Snake King",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Snake King",
        categories: ["arcade"],
        created_at: "2021-03-03T11:19:59.176Z",
        gamePlays: 0,
      },
      {
        code: "r1K-J3TQ5Ar",
        nameEn: "Word Finder",
        battleSupported: false,
        rating: 4,
        totalRating: 4,
        name: "Word Finder",
        categories: ["puzzleLogic"],
        created_at: "2021-04-27T06:23:41.379Z",
        gamePlays: 0,
      },
      {
        code: "rkWfy2pXq0r",
        nameEn: "Fruit Chop",
        battleSupported: false,
        rating: 4,
        totalRating: 1,
        name: "Fruit Chop",
        categories: ["arcade"],
        created_at: "2021-04-28T15:17:18.887Z",
        gamePlays: 0,
      },
      {
        code: "r1zG1h6m90H",
        nameEn: "Candy Fiesta",
        battleSupported: false,
        rating: 3.75,
        totalRating: 2,
        name: "Candy Fiesta",
        categories: ["puzzleLogic"],
        created_at: "2021-05-05T15:30:12.792Z",
        gamePlays: 0,
      },
      {
        code: "Bk9ynTQqCB",
        nameEn: "Archery Champs",
        battleSupported: false,
        rating: 4,
        totalRating: 1,
        name: "Archery Champs",
        categories: ["sportsRacing"],
        created_at: "2021-06-10T16:30:16.780Z",
        gamePlays: 0,
      },
      {
        code: "rk7G6Mkvcym",
        nameEn: "Street Dunkies",
        battleSupported: false,
        rating: 4,
        totalRating: 1,
        name: "Street Dunkies",
        categories: ["sportsRacing"],
        created_at: "2021-07-27T10:45:42.230Z",
        gamePlays: 0,
      },
      {
        code: "H1CWk36mq0S",
        nameEn: "Crossbar Shots",
        battleSupported: false,
        rating: 3.33,
        totalRating: 3,
        name: "Crossbar Shots",
        categories: ["sportsRacing"],
        created_at: "2021-09-06T08:59:47.320Z",
        gamePlays: 0,
      },
      {
        code: "HkTQJhTXqRS",
        nameEn: "Boulder Blast",
        battleSupported: false,
        rating: 2.8,
        totalRating: 5,
        name: "Boulder Blast",
        categories: ["action"],
        created_at: "2021-09-06T08:59:55.870Z",
        gamePlays: 0,
      },
      {
        code: "S1Ne12TQqCH",
        nameEn: "Dunk Shot",
        battleSupported: false,
        rating: 3.5,
        totalRating: 1,
        name: "Dunk Shot",
        categories: ["sportsRacing"],
        created_at: "2021-09-23T16:10:50.844Z",
        gamePlays: 0,
      },
      {
        code: "r1xZyhTQ50r",
        nameEn: "Dunk Draw",
        battleSupported: false,
        rating: 2,
        totalRating: 1,
        name: "Dunk Draw",
        categories: ["arcade"],
        created_at: "2021-10-06T11:35:27.431Z",
        gamePlays: 0,
      },
      {
        code: "r1u7J3TmqCS",
        nameEn: "Hero Archer",
        battleSupported: false,
        rating: 2,
        totalRating: 1,
        name: "Hero Archer",
        categories: ["adventure"],
        created_at: "2021-10-20T17:55:46.771Z",
        gamePlays: 0,
      },
      {
        code: "QPcVkaHi1",
        nameEn: "Ninja Speed Runner",
        battleSupported: false,
        rating: 3,
        totalRating: 2,
        name: "Ninja Speed Runner",
        categories: ["action"],
        created_at: "2021-11-22T15:08:49.709Z",
        gamePlays: 0,
      },
      {
        code: "UYiznUAya",
        nameEn: "Blazing Blades",
        battleSupported: false,
        rating: 2.17,
        totalRating: 3,
        name: "Blazing Blades",
        categories: ["action"],
        created_at: "2021-11-25T10:00:25.199Z",
        gamePlays: 0,
      },
      {
        code: "hfPOimYqY",
        nameEn: "Merge Mania",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Merge Mania",
        categories: ["strategy"],
        created_at: "2021-12-08T08:52:12.268Z",
        gamePlays: 0,
      },
      {
        code: "ryJGkhT7qAB",
        nameEn: "Bubble Smash",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Bubble Smash",
        categories: ["puzzleLogic"],
        created_at: "2022-02-21T13:46:19.785Z",
        gamePlays: 0,
      },
      {
        code: "zMxz8LNrp",
        nameEn: "Spell Wizard",
        battleSupported: false,
        rating: 2,
        totalRating: 1,
        name: "Spell Wizard",
        categories: ["strategy"],
        created_at: "2022-02-21T13:46:24.157Z",
        gamePlays: 0,
      },
      {
        code: "SkF7yhp7q0B",
        nameEn: "Darts",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Darts",
        categories: ["sportsRacing"],
        created_at: "2022-04-22T10:01:40.025Z",
        gamePlays: 0,
      },
      {
        code: "wMm3YDfJC",
        nameEn: "Pizza Dash",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Pizza Dash",
        categories: ["arcade"],
        created_at: "2022-06-03T10:51:30.691Z",
        gamePlays: 0,
      },
      {
        code: "hgempP8Sc",
        nameEn: "Pool Master",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Pool Master",
        categories: ["sportsRacing"],
        created_at: "2022-07-22T18:05:52.422Z",
        gamePlays: 0,
      },
      {
        code: "H15Qk3pQ5CH",
        nameEn: "Hoopball Legends",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Hoopball Legends",
        categories: ["arcade"],
        created_at: "2022-08-11T08:50:37.297Z",
        gamePlays: 0,
      },
      {
        code: "SJRX12TXcRH",
        nameEn: "Ludo Dash",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Ludo Dash",
        categories: ["strategy"],
        created_at: "2022-08-19T11:17:39.654Z",
        gamePlays: 0,
      },
      {
        code: "Hk3bj6nMdgb",
        nameEn: "Laser Locked",
        battleSupported: false,
        rating: 3.75,
        totalRating: 0,
        name: "Laser Locked",
        categories: ["puzzleLogic"],
        created_at: "2022-09-29T10:19:56.186Z",
        gamePlays: 0,
      },
      {
        code: "ByQxJnp7qRB",
        nameEn: "ZUNO",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "ZUNO",
        categories: ["strategy"],
        created_at: "2022-11-23T06:52:09.372Z",
        gamePlays: 0,
      },
      {
        code: "REwFeKcoN",
        nameEn: "Gun Master",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Gun Master",
        categories: ["action"],
        created_at: "2022-12-29T07:59:51.387Z",
        gamePlays: 0,
      },
      {
        code: "Sy8y2aQ9CB",
        nameEn: "Quiz Champions",
        battleSupported: false,
        rating: 4,
        totalRating: 1,
        name: "Quiz Champions",
        categories: ["puzzleLogic"],
        created_at: "2023-01-11T10:23:59.290Z",
        gamePlays: 0,
      },
      {
        code: "p7HOjYF4O",
        nameEn: "Rampage Racer",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Rampage Racer",
        categories: ["sportsRacing"],
        created_at: "2023-02-01T12:00:30.496Z",
        gamePlays: 0,
      },
      {
        code: "mKZZW9NXW",
        nameEn: "Fruity Fiesta",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Fruity Fiesta",
        categories: ["arcade"],
        created_at: "2023-02-16T13:38:31.466Z",
        gamePlays: 0,
      },
      {
        code: "H1Wzaf1wqyQ",
        nameEn: "Hipster Tennis",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Hipster Tennis",
        categories: ["sportsRacing"],
        created_at: "2023-07-05T09:49:00.834Z",
        gamePlays: 0,
      },
      {
        code: "Cg8EBuMp7",
        nameEn: "Hill Top Tanks",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Hill Top Tanks",
        categories: ["action"],
        created_at: "2023-07-19T12:19:17.539Z",
        gamePlays: 0,
      },
      {
        code: "Bk9MJhpX5Ar",
        nameEn: "Witch Flight",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Witch Flight",
        categories: ["adventure"],
        created_at: "2023-09-15T11:15:06.699Z",
        gamePlays: 0,
      },
      {
        code: "B1PfyhpQ5Ar",
        nameEn: "Shape Smash",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Shape Smash",
        categories: ["strategy"],
        created_at: "2023-09-20T19:08:14.286Z",
        gamePlays: 0,
      },
      {
        code: "PdIZyZNAe",
        nameEn: "Dragon Annihilation",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Dragon Annihilation",
        categories: ["strategy"],
        created_at: "2023-10-06T07:27:08.221Z",
        gamePlays: 0,
      },
      {
        code: "yr4TqJhLr",
        nameEn: "Blaze Rider",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Blaze Rider",
        categories: ["sportsRacing"],
        created_at: "2023-10-09T16:04:07.122Z",
        gamePlays: 0,
      },
      {
        code: "wIRrQjVa7",
        nameEn: "Hyperdrive Swinger",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Hyperdrive Swinger",
        categories: ["sportsRacing"],
        created_at: "2023-10-09T16:04:08.992Z",
        gamePlays: 0,
      },
      {
        code: "Bkozyhpmc0H",
        nameEn: "Hop Kangaroo Hop",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Hop Kangaroo Hop",
        categories: ["arcade"],
        created_at: "2023-11-02T05:21:45.313Z",
        gamePlays: 0,
      },
      {
        code: "PLQTtp9Ei",
        nameEn: "Slide And Divide",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Slide And Divide",
        categories: ["strategy"],
        created_at: "2023-12-29T07:19:46.066Z",
        gamePlays: 0,
      },
      {
        code: "6tEYzgxz2",
        nameEn: "Soccer Wizard",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Soccer Wizard",
        categories: ["sportsRacing"],
        created_at: "2024-01-05T08:31:54.554Z",
        gamePlays: 0,
      },
      {
        code: "WaQryduJa",
        nameEn: "Football Kickoff",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Football Kickoff",
        categories: ["sportsRacing"],
        created_at: "2024-02-02T05:04:28.659Z",
        gamePlays: 0,
      },
      {
        code: "XxembtJs1",
        nameEn: "Merge The Gems",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Merge The Gems",
        categories: ["strategy"],
        created_at: "2024-02-08T06:40:32.592Z",
        gamePlays: 0,
      },
      {
        code: "on1jVCbBn",
        nameEn: "Animal Connection",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Animal Connection",
        categories: ["puzzleLogic"],
        created_at: "2024-02-23T06:40:14.302Z",
        gamePlays: 0,
      },
      {
        code: "Umfd7yvMd",
        nameEn: "Viking Siege",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Viking Siege",
        categories: ["strategy"],
        created_at: "2024-03-29T05:09:44.579Z",
        gamePlays: 0,
      },
      {
        code: "Rt5ytrd0m",
        nameEn: "Kingdom Fight 2.0",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Kingdom Fight 2.0",
        categories: ["strategy"],
        created_at: "2024-04-17T14:09:27.100Z",
        gamePlays: 0,
      },
      {
        code: "mfuw6HsxP",
        nameEn: "Templok",
        battleSupported: false,
        rating: 0,
        totalRating: 0,
        name: "Templok",
        categories: ["puzzleLogic"],
        created_at: "2024-04-24T05:00:52.506Z",
        gamePlays: 0,
      },
    ],
    categories: {
      puzzleLogic: "Puzzle & Logic",
      strategy: "Strategy",
      sportsRacing: "Sports & Racing",
      arcade: "Arcade",
      adventure: "Adventure",
      action: "Action",
    },
    trendingGames: [
      "HJ-72IFXyg",
      "HyV_Nm-kK",
      "Sk728YXJx",
      "BJlg94zA76",
      "B1MfIa4QCg",
      "S1-bxXI39",
    ],
    gameOfTheWeek: "HJ-72IFXyg",
    newlyAddedGames: [
      "wIRrQjVa7",
      "Bkozyhpmc0H",
      "PLQTtp9Ei",
      "6tEYzgxz2",
      "WaQryduJa",
      "XxembtJs1",
      "on1jVCbBn",
      "Umfd7yvMd",
      "Rt5ytrd0m",
      "mfuw6HsxP",
    ],
  },
  error: "",
  code: "SUCCESS",
};
